language: perl
dist: trusty
sudo: required

before_install:
  - sudo apt-get update -q
  - make deps
  - make dev-deps

install:
  - npm install
  - bower install

script:
  - make vendor
  - make dist
  - bash ./test.sh
